languages_to_scrape = [
    "Arabic",
    "Bengali",
    "Bulgarian",
    "Cantonese",
    "Catalan",
    "Chinese",
    "Croatian",
    "Czech",
    "Danish",
    "Dari",
    "Dutch",
    "Estonian",
    "Finnish",
    "French",
    "German",
    "Greek (Ancient)",
    "Greek (Modern)",
    "Hebrew (Modern)",
    "Hindi",
    "Indonesian",
    "Icelandic",
    "Irish Gaelic",
    "Italian",
    "Lithuanian",
    "Japanese",
    "Korean",
    "Latin",
    "Lingala",
    "Malay",
    "Maori",
    "Marathi",
    "Norwegian",
    "Pashto",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Romanian",
    "Russian",
    "Sanskrit",
    "Serbian",
    "Sinhala",
    "Slovak",
    "Slovenian",
    "Spanish",
    "Swahili",
    "Swedish",
    "Tagalog",
    "Tamil",
    "Telugu",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Urdu",
    "Vietnamese",
]
